version: '2'
services:
   puller:
      environment:
        - mode=pull
      build: .
      image: nanomsg_tester
      volumes: 
         - /tmp:/tmp
   pusher:
      environment:
        - mode=push
      image: nanomsg_tester
      volumes: 
         - /tmp:/tmp
